//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Organizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aspnet_Organizations()
        {
            this.aspnet_RolesInOrganization = new HashSet<aspnet_RolesInOrganization>();
            this.aspnet_UsersInOrganization = new HashSet<aspnet_UsersInOrganization>();
            this.Media_Programmes = new HashSet<Media_Programmes>();
        }
    
        public System.Guid ApplicationID { get; set; }
        public System.Guid OrganizationID { get; set; }
        public System.Guid ParentOrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public System.Guid CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> Loai { get; set; }
        public string IdPath { get; set; }
        public string Path { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> HasChild { get; set; }
    
        public virtual aspnet_Organizations aspnet_Organizations1 { get; set; }
        public virtual aspnet_Organizations aspnet_Organizations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_RolesInOrganization> aspnet_RolesInOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersInOrganization> aspnet_UsersInOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media_Programmes> Media_Programmes { get; set; }
    }
}
