//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsd_System_Tracking
    {
        public long Id { get; set; }
        public System.Guid UserId { get; set; }
        public string FullName { get; set; }
        public System.DateTime LoggedOnDate { get; set; }
        public string Object { get; set; }
        public string Action { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string TrackingZone { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
