//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Item_Attribute
    {
        public System.Guid CatalogItemAttributeId { get; set; }
        public System.Guid CatalogItemId { get; set; }
        public System.Guid MetadataFieldId { get; set; }
        public string MetadataFieldName { get; set; }
        public string NvarcharValue { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<System.DateTime> DatetimeValue { get; set; }
        public Nullable<bool> BitValue { get; set; }
        public string VarcharValue { get; set; }
        public Nullable<System.Guid> GuidValue { get; set; }
        public string DataType { get; set; }
        public string MetadataFieldCode { get; set; }
        public string JsonValue { get; set; }
        public string JsonGuidValue { get; set; }
        public Nullable<System.DateTime> TimeValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<System.DateTime> YearValue { get; set; }
        public Nullable<System.DateTime> MonthValue { get; set; }
        public Nullable<int> TypeDateTime { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        public virtual Catalog_Item Catalog_Item { get; set; }
        public virtual Metadata_Field Metadata_Field { get; set; }
    }
}
