//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Field
    {
        public System.Guid FieldId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string FormlyContent { get; set; }
        public bool IsRecordCommonField { get; set; }
        public bool IsDocumentCommonField { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.Guid LastModifiedByUserId { get; set; }
        public bool DisplayCatalog { get; set; }
        public bool DisplayReport { get; set; }
        public bool DisplayReader { get; set; }
        public bool DisplayReportSearch { get; set; }
        public bool DisplayReaderSearch { get; set; }
        public Nullable<System.Guid> CatalogMasterId { get; set; }
        public Nullable<int> FieldWidth { get; set; }
        public string DataType { get; set; }
        public string CatalogCode { get; set; }
        public string fieldName_New { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        public virtual Catalog_Master Catalog_Master { get; set; }
    }
}
