//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_Item()
        {
            this.Catalog_Item_Attribute = new HashSet<Catalog_Item_Attribute>();
        }
    
        public System.Guid CatalogItemId { get; set; }
        public System.Guid MappedTermId { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserId { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Item_Attribute> Catalog_Item_Attribute { get; set; }
        public virtual Taxonomy_Term Taxonomy_Term { get; set; }
    }
}
