//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public System.Guid CertificateId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string SerialCert { get; set; }
        public string Cert { get; set; }
        public Nullable<bool> Used { get; set; }
        public string OwnCA { get; set; }
        public string OrganizationCA { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<int> CertType { get; set; }
        public string HsmAlias { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
