//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_InvCat_InvTemp
    {
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid InvoiceCategoryId { get; set; }
        public System.Guid InvoiceTemplateId { get; set; }
        public Nullable<bool> IsCertify { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual InvoiceCategory InvoiceCategory { get; set; }
        public virtual InvoiceTemplate InvoiceTemplate { get; set; }
    }
}
