//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectApplication
    {
        public System.Guid ConnectApplicationId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public bool IsActive { get; set; }
        public string ApplicationName { get; set; }
    }
}
