//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectWithInvoice
    {
        public System.Guid ConnectWithInvoiceId { get; set; }
        public System.Guid ConnectApplicationId { get; set; }
        public System.Guid InvoiceId { get; set; }
        public string OtherId { get; set; }
        public int Status { get; set; }
        public int StatusInvoice { get; set; }
        public int AdjustmentType { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    }
}
