//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid CustomerId { get; set; }
        public string Name { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string RepresentPerson { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string SignatureImage { get; set; }
        public string SerialCert { get; set; }
        public Nullable<System.Guid> DeliverMethod { get; set; }
        public string CC { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> InvoiceStatus { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string IdentityNumber { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Company Company { get; set; }
    }
}
