//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision_Company_Invoice
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DecisionId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> InvoiceCategoryId { get; set; }
        public Nullable<System.Guid> InvoiceTemplateId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual InvoiceCategory InvoiceCategory { get; set; }
        public virtual InvoiceTemplate InvoiceTemplate { get; set; }
    }
}
