//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Decision()
        {
            this.Decision_Company_Invoice = new HashSet<Decision_Company_Invoice>();
        }
    
        public System.Guid DecisionId { get; set; }
        public string ParentCompany { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyAddress { get; set; }
        public string DecisionNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Director { get; set; }
        public string Proponent { get; set; }
        public string Recipients { get; set; }
        public string City { get; set; }
        public string EquipmentSystem { get; set; }
        public string SoftwareApplication { get; set; }
        public string InvoiceProcess { get; set; }
        public string ProviderName { get; set; }
        public string Responsibility { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decision_Company_Invoice> Decision_Company_Invoice { get; set; }
    }
}
