//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFEntities : DbContext
    {
        public EFEntities()
            : base("name=EFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<C_DatabaseLog> C_DatabaseLog { get; set; }
        public virtual DbSet<AccessList> AccessLists { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Organizations> aspnet_Organizations { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_Roles_Scheme_Relationships> aspnet_Roles_Scheme_Relationships { get; set; }
        public virtual DbSet<aspnet_RolesInOrganization> aspnet_RolesInOrganization { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_UsersInOrganization> aspnet_UsersInOrganization { get; set; }
        public virtual DbSet<aspnet_UsersInRoles> aspnet_UsersInRoles { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<bsd_System_Tracking> bsd_System_Tracking { get; set; }
        public virtual DbSet<Catalog_Field> Catalog_Field { get; set; }
        public virtual DbSet<Catalog_Item> Catalog_Item { get; set; }
        public virtual DbSet<Catalog_Item_Attribute> Catalog_Item_Attribute { get; set; }
        public virtual DbSet<Catalog_Master> Catalog_Master { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<cms_Site> cms_Site { get; set; }
        public virtual DbSet<cms_SiteBinding> cms_SiteBinding { get; set; }
        public virtual DbSet<Comp_InvCat_InvTemp> Comp_InvCat_InvTemp { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<ConnectApplication> ConnectApplications { get; set; }
        public virtual DbSet<ConnectHistory> ConnectHistories { get; set; }
        public virtual DbSet<ConnectWithInvoice> ConnectWithInvoices { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Decision> Decisions { get; set; }
        public virtual DbSet<Decision_Company_Invoice> Decision_Company_Invoice { get; set; }
        public virtual DbSet<DM_Position> DM_Position { get; set; }
        public virtual DbSet<EmailConfig> EmailConfigs { get; set; }
        public virtual DbSet<File_version> File_version { get; set; }
        public virtual DbSet<FileExtension> FileExtensions { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileThumbnail> FileThumbnails { get; set; }
        public virtual DbSet<Folder_access> Folder_access { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<idm_Right> idm_Right { get; set; }
        public virtual DbSet<idm_RightsInRole> idm_RightsInRole { get; set; }
        public virtual DbSet<idm_RightsOfUser> idm_RightsOfUser { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceCategory> InvoiceCategories { get; set; }
        public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }
        public virtual DbSet<InvoiceTemplate> InvoiceTemplates { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Media_Programmes> Media_Programmes { get; set; }
        public virtual DbSet<Metadata> Metadatas { get; set; }
        public virtual DbSet<Metadata_Field> Metadata_Field { get; set; }
        public virtual DbSet<Metadata_Field_Template_Relationship> Metadata_Field_Template_Relationship { get; set; }
        public virtual DbSet<Metadata_Nodetype> Metadata_Nodetype { get; set; }
        public virtual DbSet<Metadata_Template> Metadata_Template { get; set; }
        public virtual DbSet<Navigation> Navigations { get; set; }
        public virtual DbSet<Navigation_Role> Navigation_Role { get; set; }
        public virtual DbSet<Node_access> Node_access { get; set; }
        public virtual DbSet<Node_files> Node_files { get; set; }
        public virtual DbSet<Node_metadata> Node_metadata { get; set; }
        public virtual DbSet<Node_ref> Node_ref { get; set; }
        public virtual DbSet<Node_tags> Node_tags { get; set; }
        public virtual DbSet<Node_type> Node_type { get; set; }
        public virtual DbSet<Node_WorkFlow> Node_WorkFlow { get; set; }
        public virtual DbSet<Node_WorkFlow_TransitionHistory> Node_WorkFlow_TransitionHistory { get; set; }
        public virtual DbSet<Node_WorkFlowExt> Node_WorkFlowExt { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<Product_Invoice> Product_Invoice { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Publish_Announcement> Publish_Announcement { get; set; }
        public virtual DbSet<Publish_Invoice_Template> Publish_Invoice_Template { get; set; }
        public virtual DbSet<Recent_files> Recent_files { get; set; }
        public virtual DbSet<Recent_folders> Recent_folders { get; set; }
        public virtual DbSet<Recent_roles> Recent_roles { get; set; }
        public virtual DbSet<Recent_users> Recent_users { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<Right_Role> Right_Role { get; set; }
        public virtual DbSet<SendEmailHistory> SendEmailHistories { get; set; }
        public virtual DbSet<SkippedInvoice> SkippedInvoices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemParameter> SystemParameters { get; set; }
        public virtual DbSet<TaxAuthority> TaxAuthorities { get; set; }
        public virtual DbSet<Taxonomy_ScopeTypes> Taxonomy_ScopeTypes { get; set; }
        public virtual DbSet<Taxonomy_Term> Taxonomy_Term { get; set; }
        public virtual DbSet<Taxonomy_Vocabulary> Taxonomy_Vocabulary { get; set; }
        public virtual DbSet<Taxonomy_VocabularyTypes> Taxonomy_VocabularyTypes { get; set; }
        public virtual DbSet<Users_Position_Relationships> Users_Position_Relationships { get; set; }
        public virtual DbSet<Workflow_Document> Workflow_Document { get; set; }
        public virtual DbSet<Workflow_DocumentTransitionHistory> Workflow_DocumentTransitionHistory { get; set; }
        public virtual DbSet<Workflow_Employee> Workflow_Employee { get; set; }
        public virtual DbSet<Workflow_Roles> Workflow_Roles { get; set; }
        public virtual DbSet<Workflow_StructDivision> Workflow_StructDivision { get; set; }
        public virtual DbSet<WorkflowGlobalParameter> WorkflowGlobalParameters { get; set; }
        public virtual DbSet<WorkflowInbox> WorkflowInboxes { get; set; }
        public virtual DbSet<WorkflowProcessInstance> WorkflowProcessInstances { get; set; }
        public virtual DbSet<WorkflowProcessInstancePersistence> WorkflowProcessInstancePersistences { get; set; }
        public virtual DbSet<WorkflowProcessInstanceStatu> WorkflowProcessInstanceStatus { get; set; }
        public virtual DbSet<WorkflowProcessScheme> WorkflowProcessSchemes { get; set; }
        public virtual DbSet<WorkflowProcessTimer> WorkflowProcessTimers { get; set; }
        public virtual DbSet<WorkflowProcessTransitionHistory> WorkflowProcessTransitionHistories { get; set; }
        public virtual DbSet<WorkflowScheme> WorkflowSchemes { get; set; }
        public virtual DbSet<WorkflowScheme_Document> WorkflowScheme_Document { get; set; }
    }
}
