//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public System.Guid Id { get; set; }
        public string From { get; set; }
        public string Password { get; set; }
        public string Smtp { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> SSL { get; set; }
        public string SendType { get; set; }
        public int Order { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string DisplayName { get; set; }
    }
}
