//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileExtension
    {
        public System.Guid FileExtensionID { get; set; }
        public System.Guid ApplicationID { get; set; }
        public string FileType { get; set; }
        public string FileExt { get; set; }
        public System.Guid CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
    }
}
