//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder_access
    {
        public System.Guid FolderAccessID { get; set; }
        public System.Guid FolderID { get; set; }
        public System.Guid AccessID { get; set; }
        public string AccessType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public System.Guid CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual AccessList AccessList { get; set; }
        public virtual Folder Folder { get; set; }
    }
}
