//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class idm_RightsInRole
    {
        public long Id { get; set; }
        public System.Guid RoleId { get; set; }
        public string RightCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual idm_Right idm_Right { get; set; }
    }
}
