//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class idm_Right
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idm_Right()
        {
            this.idm_Right1 = new HashSet<idm_Right>();
            this.idm_RightsInRole = new HashSet<idm_RightsInRole>();
            this.idm_RightsOfUser = new HashSet<idm_RightsOfUser>();
        }
    
        public string RightCode { get; set; }
        public string RightName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsGroup { get; set; }
        public int Level { get; set; }
        public string GroupCode { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idm_Right> idm_Right1 { get; set; }
        public virtual idm_Right idm_Right2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idm_RightsInRole> idm_RightsInRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idm_RightsOfUser> idm_RightsOfUser { get; set; }
    }
}
