//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Product_Invoice = new HashSet<Product_Invoice>();
        }
    
        public System.Guid InvoiceId { get; set; }
        public Nullable<System.Guid> InvoiceCategoryId { get; set; }
        public Nullable<System.Guid> InvoiceTemplateId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string Data { get; set; }
        public string Signature { get; set; }
        public Nullable<int> Converted { get; set; }
        public string KindOfService { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public string ProcessInvoiceNote { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> VatAmount0 { get; set; }
        public Nullable<decimal> GrossValue0 { get; set; }
        public Nullable<decimal> VatAmount5 { get; set; }
        public Nullable<decimal> GrossValue5 { get; set; }
        public Nullable<decimal> VatAmount10 { get; set; }
        public Nullable<decimal> GrossValue10 { get; set; }
        public Nullable<bool> Certified { get; set; }
        public string CertifiedId { get; set; }
        public string CertifiedData { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.Guid> CreationBy { get; set; }
        public Nullable<System.Guid> PublishBy { get; set; }
        public Nullable<System.Guid> PaymentMethod { get; set; }
        public string SellerAppRecordId { get; set; }
        public string InvoiceAppRecordId { get; set; }
        public string InvoiceType { get; set; }
        public string TemplateCode { get; set; }
        public string InvoiceSeries { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceName { get; set; }
        public Nullable<System.DateTime> InvoiceIssuedDate { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string InvoiceNote { get; set; }
        public Nullable<int> AdjustmentType { get; set; }
        public Nullable<System.Guid> OriginalInvoiceId { get; set; }
        public string AdditionalReferenceDesc { get; set; }
        public Nullable<System.DateTime> AdditionalReferenceDate { get; set; }
        public string SellerLegalName { get; set; }
        public string SellerTaxCode { get; set; }
        public string SellerAddressLine { get; set; }
        public string SellerPostalCode { get; set; }
        public string SellerDistrictName { get; set; }
        public string SellerCityName { get; set; }
        public string SellerCountryCode { get; set; }
        public string SellerPhoneNumber { get; set; }
        public string SellerFaxNumber { get; set; }
        public string SellerEmail { get; set; }
        public string SellerBankName { get; set; }
        public string SellerBankAccount { get; set; }
        public string SellerContactPersonName { get; set; }
        public string SellerSignedPersonName { get; set; }
        public string SellerSubmittedPersonName { get; set; }
        public string BuyerDisplayName { get; set; }
        public string BuyerLegalName { get; set; }
        public string BuyerTaxCode { get; set; }
        public string BuyerAddressLine { get; set; }
        public string BuyerPostalCode { get; set; }
        public string BuyerDistrictName { get; set; }
        public string BuyerCityName { get; set; }
        public string BuyerCountryCode { get; set; }
        public string BuyerPhoneNumber { get; set; }
        public string BuyerFaxNumber { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerBankName { get; set; }
        public string BuyerBankAccount { get; set; }
        public Nullable<decimal> SumOfTotalLineAmountWithoutVAT { get; set; }
        public Nullable<decimal> TotalAmountWithoutVAT { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public Nullable<decimal> TotalAmountWithVAT { get; set; }
        public Nullable<decimal> TotalAmountWithVATFrn { get; set; }
        public string TotalAmountWithVATInWords { get; set; }
        public Nullable<bool> IsTotalAmountPos { get; set; }
        public Nullable<bool> IsTotalVATAmountPos { get; set; }
        public Nullable<bool> IsTotalAmtWithoutVatPos { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<bool> IsDiscountAmtPos { get; set; }
        public string ProductCodes { get; set; }
        public string PortalLink { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> InvoiceStatus { get; set; }
        public Nullable<decimal> VatPercentage { get; set; }
        public Nullable<bool> ConvertedStatus { get; set; }
        public Nullable<System.DateTime> ConvertedDate { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<bool> TrangThaiXemTraCuuHoaDon { get; set; }
        public Nullable<bool> SkippedInvoiceStatus { get; set; }
        public Nullable<System.Guid> SkippedInvoiceId { get; set; }
        public Nullable<System.DateTime> CreatedDateNoSigned { get; set; }
        public Nullable<System.DateTime> CreatedDateSigned { get; set; }
        public Nullable<bool> IsCompanySignReport { get; set; }
        public Nullable<bool> IsCustomerSignReport { get; set; }
        public string ReportUrl { get; set; }
        public string ReportFileName { get; set; }
        public string BuyerCode { get; set; }
        public string ChangeReportFileName { get; set; }
        public string ChangeReportUrl { get; set; }
        public string DeleteReportFileName { get; set; }
        public string DeleteReportUrl { get; set; }
        public Nullable<bool> IsCompanySignReportChange { get; set; }
        public Nullable<bool> IsCompanySignReportDelete { get; set; }
        public Nullable<bool> IsCustomerSignReportChange { get; set; }
        public Nullable<bool> IsCustomerSignReportDelete { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string PdfUrl { get; set; }
        public Nullable<double> EndNumber { get; set; }
        public Nullable<decimal> EnvironmentFee { get; set; }
        public Nullable<double> EnvironmentTax { get; set; }
        public Nullable<System.DateTime> FromUseDate { get; set; }
        public Nullable<double> StartNumber { get; set; }
        public Nullable<System.DateTime> ToUseDate { get; set; }
        public Nullable<double> UseNumber { get; set; }
        public Nullable<decimal> AmountExchanged { get; set; }
        public Nullable<decimal> DrainageServicePrice { get; set; }
        public Nullable<decimal> DrainageServiceTaxMoney { get; set; }
        public Nullable<bool> IsOtherApp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Invoice> Product_Invoice { get; set; }
    }
}
