//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public System.Guid InvoicePaymentId { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.Guid> PaymentMethod { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentNote { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string PaymentTerm { get; set; }
        public string BankName { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    }
}
