//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceTemplate()
        {
            this.Comp_InvCat_InvTemp = new HashSet<Comp_InvCat_InvTemp>();
            this.Decision_Company_Invoice = new HashSet<Decision_Company_Invoice>();
        }
    
        public System.Guid InvoiceTemplateId { get; set; }
        public Nullable<System.Guid> InvoiceCategoryId { get; set; }
        public string TemplateName { get; set; }
        public string XmlFile { get; set; }
        public string XsltFile { get; set; }
        public string SchemaFile { get; set; }
        public string ServiceType { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceView { get; set; }
        public string IGenerator { get; set; }
        public string IViewer { get; set; }
        public string CssData { get; set; }
        public string CssLogo { get; set; }
        public string CssBackground { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<bool> IsCertify { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string TemplateCode { get; set; }
        public string BusinessArea { get; set; }
        public Nullable<int> VatType { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comp_InvCat_InvTemp> Comp_InvCat_InvTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decision_Company_Invoice> Decision_Company_Invoice { get; set; }
        public virtual InvoiceCategory InvoiceCategory { get; set; }
    }
}
