//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public System.DateTime Date { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public string ActionByUserID { get; set; }
        public string Exception { get; set; }
        public System.Guid ModuleID { get; set; }
        public string Content { get; set; }
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string ObjectType { get; set; }
        public Nullable<System.Guid> ObjectID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
