//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_Programmes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media_Programmes()
        {
            this.Node_WorkFlowExt = new HashSet<Node_WorkFlowExt>();
        }
    
        public System.Guid ApplicationID { get; set; }
        public System.Guid ProgrammeID { get; set; }
        public string ProgrammeName { get; set; }
        public string BroadcastDate { get; set; }
        public string BroadcastTime { get; set; }
        public Nullable<System.Guid> OrganizationID { get; set; }
        public System.Guid CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual aspnet_Organizations aspnet_Organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Node_WorkFlowExt> Node_WorkFlowExt { get; set; }
    }
}
