//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata_Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metadata_Field()
        {
            this.Catalog_Item_Attribute = new HashSet<Catalog_Item_Attribute>();
            this.Metadata_Field_Template_Relationship = new HashSet<Metadata_Field_Template_Relationship>();
        }
    
        public System.Guid MetadataFieldId { get; set; }
        public string Name { get; set; }
        public string DataType { get; set; }
        public string FormlyContent { get; set; }
        public string Description { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserId { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Item_Attribute> Catalog_Item_Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Metadata_Field_Template_Relationship> Metadata_Field_Template_Relationship { get; set; }
    }
}
