//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata_Field_Template_Relationship
    {
        public long Id { get; set; }
        public System.Guid MetadataTemplateId { get; set; }
        public System.Guid MetadataFieldId { get; set; }
        public int Order { get; set; }
        public int Status { get; set; }
    
        public virtual Metadata_Field Metadata_Field { get; set; }
        public virtual Metadata_Template Metadata_Template { get; set; }
    }
}
