//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata_Nodetype
    {
        public System.Guid MetaNodeTypeID { get; set; }
        public System.Guid MetadataID { get; set; }
        public string MetadataName { get; set; }
        public System.Guid NoteTypeID { get; set; }
    
        public virtual Metadata Metadata { get; set; }
        public virtual Node_type Node_type { get; set; }
    }
}
