//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation_Role
    {
        public System.Guid NavigationRoleId { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid NavigationId { get; set; }
        public Nullable<System.Guid> FromSubNavigation { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        public virtual Navigation Navigation { get; set; }
    }
}
