//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_ref
    {
        public System.Guid ID { get; set; }
        public System.Guid NodeID { get; set; }
        public System.Guid NodeRefID { get; set; }
        public string RefType { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Node Node1 { get; set; }
    }
}
