//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_metadata
    {
        public System.Guid ID { get; set; }
        public System.Guid NodeID { get; set; }
        public System.Guid MetadataID { get; set; }
        public string MetadataName { get; set; }
        public string MetadataValue { get; set; }
        public System.Guid CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public int Status { get; set; }
    
        public virtual Metadata Metadata { get; set; }
        public virtual Node Node { get; set; }
    }
}
