//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_WorkFlowExt
    {
        public System.Guid ID { get; set; }
        public System.Guid NodeWorkFlowID { get; set; }
        public Nullable<System.Guid> ProgrammeID { get; set; }
        public string TapeCode { get; set; }
        public string EpisodeTitle { get; set; }
    
        public virtual Media_Programmes Media_Programmes { get; set; }
        public virtual Node_WorkFlow Node_WorkFlow { get; set; }
    }
}
