//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_tags
    {
        public System.Guid ID { get; set; }
        public System.Guid NodeID { get; set; }
        public System.Guid TermID { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Taxonomy_Term Taxonomy_Term { get; set; }
    }
}
