//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Node_type()
        {
            this.Metadata_Nodetype = new HashSet<Metadata_Nodetype>();
            this.Nodes = new HashSet<Node>();
        }
    
        public System.Guid NodeTypeID { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Hastitle { get; set; }
        public Nullable<int> Haslabel { get; set; }
        public Nullable<int> Custom { get; set; }
        public Nullable<int> Modified { get; set; }
        public Nullable<int> Locked { get; set; }
        public Nullable<int> Disabled { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.Guid LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Metadata_Nodetype> Metadata_Nodetype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Node> Nodes { get; set; }
    }
}
