//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_WorkFlow_TransitionHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid NodeId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string AllowedToUserNames { get; set; }
        public Nullable<System.DateTime> TransitionTime { get; set; }
        public long Order { get; set; }
        public Nullable<System.DateTime> TransitionTimeForSort { get; set; }
        public string InitialState { get; set; }
        public string DestinationState { get; set; }
        public string Command { get; set; }
        public string Comment { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
