//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> TypeOfProduct { get; set; }
        public Nullable<System.Guid> Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string BarCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> NodeId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<decimal> PriceBeforeVAT { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<decimal> AmountBeforeVAT { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<decimal> PriceAfterVAT { get; set; }
        public Nullable<decimal> TotalAmountAfterVAT { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string UnitName { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
