//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Invoice
    {
        public System.Guid ProductInvoiceId { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ItemTotalAmountWithoutVat { get; set; }
        public Nullable<decimal> VatPercentage { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<bool> Promotion { get; set; }
        public Nullable<decimal> AdjustmentVatAmount { get; set; }
        public Nullable<bool> IsIncreaseItem { get; set; }
        public Nullable<decimal> ItemTotalAmountWithVat { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<int> ItemType { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
