//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish_Announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publish_Announcement()
        {
            this.Publish_Invoice_Template = new HashSet<Publish_Invoice_Template>();
        }
    
        public System.Guid PublishAnnouncementId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public Nullable<System.Guid> TaxAuthorityId { get; set; }
        public string Delimiter { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Representative { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publish_Invoice_Template> Publish_Invoice_Template { get; set; }
    }
}
