//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right_Role
    {
        public System.Guid RightRoleID { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid RightID { get; set; }
        public string RightName { get; set; }
        public string RightCode { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual Right Right { get; set; }
    }
}
