//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy_Term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxonomy_Term()
        {
            this.Catalog_Item = new HashSet<Catalog_Item>();
            this.Catalog_Master = new HashSet<Catalog_Master>();
            this.Node_tags = new HashSet<Node_tags>();
        }
    
        public System.Guid TermId { get; set; }
        public System.Guid VocabularyId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Weight { get; set; }
        public System.Guid TermLeft { get; set; }
        public System.Guid TermRight { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public System.Guid ApplicationID { get; set; }
        public Nullable<int> Order { get; set; }
        public string VocabularyCode { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public string IdPath { get; set; }
        public string Path { get; set; }
        public Nullable<int> Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Item> Catalog_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Master> Catalog_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Node_tags> Node_tags { get; set; }
        public virtual Taxonomy_Vocabulary Taxonomy_Vocabulary { get; set; }
    }
}
