//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy_VocabularyTypes
    {
        public System.Guid VocabularyTypeID { get; set; }
        public string VocabularyType { get; set; }
        public System.Guid ApplicationID { get; set; }
    }
}
