//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Position_Relationships
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public Nullable<System.Guid> Position_Id { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    }
}
