//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowScheme()
        {
            this.aspnet_Roles_Scheme_Relationships = new HashSet<aspnet_Roles_Scheme_Relationships>();
            this.WorkflowScheme_Document = new HashSet<WorkflowScheme_Document>();
        }
    
        public string Code { get; set; }
        public string Scheme { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DisplayStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_Roles_Scheme_Relationships> aspnet_Roles_Scheme_Relationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowScheme_Document> WorkflowScheme_Document { get; set; }
    }
}
