//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowProcessScheme
    {
        public System.Guid Id { get; set; }
        public string Scheme { get; set; }
        public string DefiningParameters { get; set; }
        public string DefiningParametersHash { get; set; }
        public string SchemeCode { get; set; }
        public bool IsObsolete { get; set; }
    }
}
