//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowScheme_Document
    {
        public long Id { get; set; }
        public string SchemeCode { get; set; }
        public System.Guid DocumentId { get; set; }
    
        public virtual Workflow_Document Workflow_Document { get; set; }
        public virtual WorkflowScheme WorkflowScheme { get; set; }
    }
}
