//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowProcessTransitionHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid ProcessId { get; set; }
        public string ExecutorIdentityId { get; set; }
        public string ActorIdentityId { get; set; }
        public string FromActivityName { get; set; }
        public string ToActivityName { get; set; }
        public string ToStateName { get; set; }
        public System.DateTime TransitionTime { get; set; }
        public string TransitionClassifier { get; set; }
        public bool IsFinalised { get; set; }
        public string FromStateName { get; set; }
        public string TriggerName { get; set; }
    }
}
