//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC.AUTHEN.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workflow_Document()
        {
            this.Workflow_DocumentTransitionHistory = new HashSet<Workflow_DocumentTransitionHistory>();
            this.WorkflowScheme_Document = new HashSet<WorkflowScheme_Document>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public System.Guid AuthorId { get; set; }
        public Nullable<System.Guid> EmloyeeControlerId { get; set; }
        public decimal Sum { get; set; }
        public string State { get; set; }
        public string StateName { get; set; }
        public Nullable<bool> IsDenialPreExecute { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workflow_DocumentTransitionHistory> Workflow_DocumentTransitionHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowScheme_Document> WorkflowScheme_Document { get; set; }
    }
}
